/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.projet.fenetre;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import ma.projet.beans.Developpeur;
import ma.projet.beans.DirecteurGeneral;
import ma.projet.beans.Manager;
import ma.projet.service.DeveloppeurService;
import ma.projet.service.ManagerService;

/**
 *
 * @author kor
 */
public class CouchePresentation extends javax.swing.JFrame {

    private ArrayList<String> devs = new ArrayList<String>();
    private DefaultListModel liste = new DefaultListModel();

    /**
     * Creates new form CouchePresentation
     */
    public CouchePresentation() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Entreprise");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("RAMI (Directeur Général)");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("AMALI (Developpeur)");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("SADDIK (Manager)");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("SEBIHI (Developpeur)");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("NOUARI (Developpeur)");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        liste.clear();
        devs.clear();  
        DeveloppeurService ds = new DeveloppeurService();
        ManagerService ms = new ManagerService();
        DefaultMutableTreeNode node = null;

        if (jTree1.getSelectionPath() != null) {
            node = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();

            if (node.getParent().toString().equals("RAMI (Directeur Général)")) {
                if (node.toString().equals("AMALI (Developpeur)")) {
                    ArrayList<Developpeur> devss = (ArrayList<Developpeur>) ds.getAll();
                    for (Developpeur d : devss) {
                        if (d.getNom().equals("AMALI")) {
                            devs.add(d.toString());
                        }
                    }
                } else if (node.toString().equals("SADDIK (Manager)")) {
                    ArrayList<Manager> managers = (ArrayList<Manager>) ms.getAll();
                    for (Manager m : managers) {
                        if (m.getNom().equals("SADDIK")) {
                            devs.add(m.toString());
                        }
                    }
                }
            } else if (node.getParent().toString().equals("SADDIK (Manager)")) {
                if (node.toString().equals("NOUARI (Developpeur)")) {
                    ArrayList<Developpeur> devss = (ArrayList<Developpeur>) ds.getAll();
                    for (Developpeur d : devss) {
                        if (d.getNom().equals("NOUARI")) {
                            devs.add(d.toString());
                        }
                    }
                } else if (node.toString().equals("SEBIHI (Developpeur)")) {
                    ArrayList<Developpeur> devss = (ArrayList<Developpeur>) ds.getAll();
                    for (Developpeur d : devss) {
                        if (d.getNom().equals("SEBIHI")) {
                            devs.add(d.toString());
                        }
                    }
                }
            } else if (node.getParent().toString().equals("Entreprise")) {
                if (node.toString().equals("RAMI (Directeur Général)")) {
                    ArrayList<Manager> managers = (ArrayList<Manager>) ms.getAll();
                    for (Manager m : managers) {
                        if (m.getNom().equals("RAMI")) {
                            devs.add(m.toString());
                        }
                    }
                }
            }
            

            // Update the list model
            for (String dev : devs) {
                liste.addElement(dev);
            }
            jList1.setModel(liste);
        }


    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CouchePresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CouchePresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CouchePresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CouchePresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CouchePresentation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
